START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220206092253_remove_test_table') THEN
    CREATE TABLE "user".test (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        CONSTRAINT "PK_test" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220206092253_remove_test_table') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220206092253_remove_test_table';
    END IF;
END $EF$;
COMMIT;

