START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220123170109_add_test_table') THEN
    CREATE TABLE "user".test (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        CONSTRAINT "PK_test" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220123170109_add_test_table') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220123170109_add_test_table', '6.0.0');
    END IF;
END $EF$;
COMMIT;

