GET http://localhost:26169/users
Authorization: Bearer eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOjEsImVtYWlsIjoiYWRtaW5AbHVrYXN6cnlkemtvd3NraS5wbCIsInJvbGUiOlsiYWRtaW4iXSwibmJmIjoxNjM1Nzk1NjIzLCJleHAiOjE2MzU3OTYyMjMsImlhdCI6MTYzNTc5NTYyM30.TFNr0ADy0oRf7DEyUGmygxW4wyop2rYT0FPJX1dKtVBT6Ngtl3k_U6HV452ywFW-X8dz4-rnxe3OkzHGRZLMu3X551E3GA_HIZ0IfKqyAslx5N0hfMxxxr0s1hGlx0HvUZpUy9iwNji19tI00K-lbiFx3x7Ky9OLmLoJEKn6P-yAtpJpdaCwYcx04MsrzVR_-2I2RHL6PPkVJO7lHNi20DyZ_RyS4zCblBNWiyhwgxgaTuKzimFr51JNdwIRWoFauSYav1Tsk9QfPbgHOF9Q_U3wOy03MUjnr3LtgZEgnEHzoUETNUiMX3q1RjN2R9nt7KTedb_ppx_Yd6JGhwlIrSz3mYu9uVOAD_K5oWno2ZIfVFQEKCORd5Aucg1pYuoFnKcmOj1eN6RaSGKl3MgK5XCsrR_uc4OMCudjKJoTkLBaZr4nna5jvWwf0SgS-K3lYfpwFHRp-7qPzLIkD30jPJhgbTBgpIk1uzlY5e8a3lzcKqMy37LhWTix8QyZnstYwGDlSLlXv7lHmj63c4L7IFKzVB0H5m1p5z10sEtP_Xk09-QktP6YeflsLQ66bu3Rg3k7WWZAUi8cLNqIKARyaiLwzw-Y1UxMcMfWmfaWpVrvg33kgSNiy2OQ2nTtiOhnuelvL7WdJ8Jw0rX7ps4Eyk5V5mr_DPuDRY0uNJhFBKI