name: Docker image creation

on:
  push:
    tags:
      - "v*.*.*"
      
env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: lrydzkowski/r-systems-auth
  SQL_UP_IMAGE_NAME: lrydzkowski/r-systems-auth-sql-up
  SQL_DOWN_IMAGE_NAME: lrydzkowski/r-systems-auth-sql-down
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Getting the version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Signing in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extracting metadata (tags, labels) for an application docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}

      # Building an application docker image

      - name: Building an application docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Checking SQL migration files existence
      
      - name: Checking SQL migration files existence
        id: checking_migration_sql_files
        uses: andstor/file-existence-action@v1
        with:
          files: "R.Systems.Auth.Infrastructure.Db/_Assets/SQL/${{ steps.get_version.outputs.VERSION }}_up.sql, R.Systems.Auth.Infrastructure.Db/_Assets/SQL/${{ steps.get_version.outputs.VERSION }}_down.sql"

      # SQL migration up
          
      - name: Extracting metadata (tags, labels) for SQL migration up docker image
        if: steps.checking_migration_sql_files.outputs.files_exists == 'true'
        id: meta_sql_up
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.SQL_UP_IMAGE_NAME }}
          
      - name: Building SQL migration up image
        if: steps.checking_migration_sql_files.outputs.files_exists == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileSQLMigrationUp
          push: true
          tags: ${{ steps.meta_sql_up.outputs.tags }}
          labels: ${{ steps.meta_sql_up.outputs.labels }}
          build-args: version=${{ steps.get_version.outputs.VERSION }}

      # SQL migration down
          
      - name: Extracting metadata (tags, labels) for SQL migration down docker image
        if: steps.checking_migration_sql_files.outputs.files_exists == 'true'
        id: meta_sql_down
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.SQL_DOWN_IMAGE_NAME }}
          
      - name: Building SQL migration down image
        if: steps.checking_migration_sql_files.outputs.files_exists == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileSQLMigrationDown
          push: true
          tags: ${{ steps.meta_sql_down.outputs.tags }}
          labels: ${{ steps.meta_sql_down.outputs.labels }}
          build-args: version=${{ steps.get_version.outputs.VERSION }}