name: CI to GitHub Container Registry

on:
  push:
    tags:
      - "v*.*.*"
      
env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: lrydzkowski/r-systems-auth
  SQL_UP_IMAGE_NAME: lrydzkowski/r-systems-auth-sql-up
  SQL_DOWN_IMAGE_NAME: lrydzkowski/r-systems-auth-sql-down
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for app docker container
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}

      - name: Build app container and push it
        id: docker_app_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Check SQL migration up file existence
        id: check_migration_sql_files
        uses: andstor/file-existence-action@v1
        with:
          files: "R.Systems.Auth.Infrastructure.Db/_Assets/SQL/${{ steps.get_version.outputs.VERSION }}_up.sql, R.Systems.Auth.Infrastructure.Db/_Assets/SQL/${{ steps.get_version.outputs.VERSION }}_down.sql"
          
      - name: Extract metadata (tags, labels) for SQL up migration docker container
        if: steps.check_migration_sql_files.outputs.files_exists == 'true'
        id: meta_sql_up
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.SQL_UP_IMAGE_NAME }}
          
      - name: Build SQL migration up container and push it
        if: steps.check_migration_sql_files.outputs.files_exists == 'true'
        id: docker_sql_up_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileSQLMigrationUp
          push: true
          tags: ${{ steps.meta_sql_up.outputs.tags }}
          labels: ${{ steps.meta_sql_up.outputs.labels }}
          build-args: version=${{ steps.get_version.outputs.VERSION }}
          
      - name: Extract metadata (tags, labels) for SQL down migration docker container
        if: steps.check_migration_sql_files.outputs.files_exists == 'true'
        id: meta_sql_down
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.SQL_DOWN_IMAGE_NAME }}
          
      - name: Build SQL migration down container and push it
        if: steps.check_migration_sql_files.outputs.files_exists == 'true'
        id: docker_sql_down_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileSQLMigrationDown
          push: true
          tags: ${{ steps.meta_sql_down.outputs.tags }}
          labels: ${{ steps.meta_sql_down.outputs.labels }}
          build-args: version=${{ steps.get_version.outputs.VERSION }}